### ISSUE TITLE
devops-project-samples - ARM Template - DevOps Project

### ISSUE THREAD

**Issue by Zuldajri** [microsoft/devops-project-samples#119]
Hello,

I'm having a hard time using the ARM Template to create a DevOps Project using the Project Samples.

What I'm trying to do is to create an ARM Template that would have the same result as what you can do from the Azure Portal:
--> Create the DevOps Account --> Create the Project --> Bootstrap the CI/CD pipeline create the master, create the build and then the release to the production environment (Azure App,...).

Maybe I'm doing it wrong.
I have some questions regarding how to do it:
1) Should I use the ARM template that is configuring the project with the BootstrapPipelineTemplate?
https://github.com/Microsoft/devops-project-samples/blob/master/armtemplates/devopsproject/template.json
or should I use the new feature pipelineBootstrapConfigurations?
https://docs.microsoft.com/en-us/azure/templates/microsoft.visualstudio/2018-08-01-preview/account/project

2) Do you plan to update the ARM template with the new feature?

3) Does the ARM template from the DevOps Project take care of creating the target environment? or is it something that I would have to add up (meaning the Azure App, the AKS...)? 
I'm wondering as the ARM templates are being copied into the Azure Repos.
Besides, by exporting some DevOps Project deployments, I get some info:

 "PipelineBootstrapConfigurations": [
                            {
                                "name": "[parameters('projectSettings').projectName]",
                                "templateId": "ms.vss-continuous-delivery-pipeline-templates.expressjs-aks",
                                "templateParameters": {
                                    "subscriptionId": "********-****-****-****-***********",
                                    "clusterName": "devkubnodetest",
                                    "location": "West Europe",
                                    "resourceGroup": "devkubnodetest-rg",
                                    "appInsightLocation": "West Europe",
                                    "kubernetesVersion": "1.10.8",
                                    "nodeCount": "3",
                                    "nodeSize": "Standard_D2_v2",
                                    "omsLocation": "West Europe",
                                    "containerRegistryName": "devkubnodetestacr",
                                    "containerRegistrySKU": "Standard",
                                    "containerRegistryLocation": "West Europe",
                                    "azureAuth": "[parameters('azureAuth')]"
                                },
                                "repository": null

4) Is there a way to get more info regarding the options that could be used for : 
    1) The bootstrapPipelineTemplate options
    2) The pipelineBootstrapConfigurations options

--> The DevOps Project ARM Apis are not helping out that much
https://docs.microsoft.com/en-us/azure/templates/microsoft.visualstudio/2018-08-01-preview/account/project

I'm actually wondering what would be within the "azureAuth" option from the PipelineBootstreapConfigurations.
Same for the repository if I wanted to point to the Microsoft/devops-project-samples repo.

Thank you so much for your help!

William

**Comment by sachinma** [comment]
Answers:
1. pipelineBootstrapConfigurations is the recommended way to use now. All the new configurations are only added to that.

2. We will track adding another sample template to use pipelineBootstrapConfigurations .

3. With "pipelineBootstrapConfigurations" target environment will be created as part of the build and release using "config as code" ARM template files.

4.  You can create the DevOps Project from [here] https://portal.azure.com/#create/Microsoft.AzureProject)  and look at the template in use to understand azureAuth option. It is essentially AAD SPN creds with appropriate permission which are used by DevOps Project during build and release.

Repository field is dependent on the template Id. Some templates work with a sample code and in that case, they would already pick the right code. Repository field is required for "Bring your own code" scenario and the template Id for those scenarios is different.

Adding @bishal-pdMSFT  to provide the API to query available templates that you can use; and what parameters are expected for each template.

**Comment by Zuldajri** [comment]
Thanks Sachin for the answers you provided, they're quite helpful.

Regarding the azureAuth option, since it is a SecureString, it gives me a null parameter :) !
"azureAuth": {
            "type": "SecureString"
        }

So I'm wondering if they should go like:
"azureAuth": {
            "clientId": "string",
           "clientSecret": "string"
        }
Just wondering the proper writing for the Service Principal, as Azure DevOps Project, from the Portal, creates it.

That would be awesome if Bishal can provide me with these infos!

Thanks for your help,
William

**Comment by bishal-pdMSFT** [comment]
@Zuldajri The API to list Pipeline Templates is `https://portalext.dev.azure.com/<organization-name>/_apis/Arm/PipelineTemplates`. Each Pipeline Template has following properties:

- Id - This is the id which you should use for `templateId` in ARM template payload
- description - this describes what kind of pipeline will this template create. You can look through the description to select a suitable template for you
- inputs - a list of inputs which this template expects. You should pass values for each of these inputs in key-value pair format to `templateParameters` field in ARM template

**Comment by bishal-pdMSFT** [comment]
AzureAuth should be a stringified JSON containing following properties:

- scheme => this should be set to "ServicePrincipal"
- parameters => this is a property containing
  - tenantid => AAD tenant Id
  - serviceprincipalid => client id of Service Principal
  - serviceprincipalkey => Key for the above Service Principal


Example :"{\\"scheme\\":\\"ServicePrincipal\\",\\"parameters\\":{\\"tenantid\\":\\"xxx\\",\\"serviceprincipalid\\":\\"xxxx\\",\\"serviceprincipalkey\\":\\"xxxx\\"}}"

Please note that this Service Principal should have "contributor" role assignment over the resource group which you would have specified in template parameters

**Comment by Zuldajri** [comment]
Thanks Bishal, with the API list I wont have to test the deployment of each template!
And thanks for the help regarding the AzureAuth.

You both helped me out a lot on this one.
I'll keep on scripting! 

Thanks

**Comment by Zuldajri** [comment]
Hello again,

I've tried using the Azure Auth.
The Service Principal is Owner.
The DevOps account creates.
Then the DevOps project fails.

I get this error:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"NotFound","message":"{\r\n \"code\": \"ProjectNotFoundWithId\",\r\n \"message\": \"Failed to create the project 'fezfzevezt'. More details: 'Configuration failed at step: 'Creating assets'. More details: The given key was not present in the dictionary..'.\",\r\n \"target\": \"GetAzureProjectOperationInternal\"\r\n}"}]}

It seems the Service connection is created within the Project, using Service Principal, but the resources don't create.

I don't know if it's enough info :) !

Thanks in advance,
William

**Comment by bishal-pdMSFT** [comment]
@Zuldajri Sorry for that. You also need to pass Object Id of service principal in AzureAuth. Add one more parameter in AzureAuth:
objectid => Object Id of "ServicePrincipal"

PS: This should actually be optional. We will see if we can fix this.

**Comment by Zuldajri** [comment]
Ok, it's working now ! 
Thank you so much Bishal!

I'll test the Bring your Own Code later on.
From what I've seen, the template id looks like :
"ms.vss-continuous-delivery-pipeline-templates.aspnet-windowswebapp-byoc"

and the repo should look like :
"repository": {
                                    "repositoryType": "GitHub",
                                    "id": "Zuldajri/myrepo",
                                    "defaultBranch": "master",
                                    "authorization": {
                                        "authorizationType": "personalAccessToken",
                                        "parameters": {
                                            "token": "************************************"


That's great ! 
Thanks to both of you !

William

**Comment by Zuldajri** [comment]
Hello,

Sorry to bring this issue back up.

I've been trying to use the "PipelineBootstrapConfigurations" ARM template, and I'm getting errors with the azureAuth.

{\"scheme\":\"ServicePrincipal\",\"parameters\":{\"tenantid\":\"xxx\",\"serviceprincipalid\":\"xxx\",\"serviceprincipalkey\":\"xxx\",\"objectid\":\"xxx\"}}

Has it been updated since then? 
I still cannot find any documentation regarding this azureAuth.

Thanks in advance,
William
