### ISSUE TITLE
YAML pipeline builddefinition

### ISSUE THREAD

**Issue by allanmoller** [microsoft/devops-project-samples#228]
First off thx for this example :-)

I have successfully deployed into my own org, but are having issues with creating a template project that uses YAML pipelines instead of old school buildDefinitions. 

i have reversed engineered it by hitting "F12" in browser to see what requests are initiated when using portal, but have not been able to create an extension that initiates a repo with a yaml pipeline. Could you give some pointers on how this could be archived?

**Comment by vineetmimrot** [comment]
You can watch this tutorial to auto-generate YAML pipeline based on your source code.
https://www.youtube.com/watch?v=ORy3OeqLZlE

https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=java%2Cyaml%2Cbrowser%2Ctfs-2018-2


Or from the existing build definition you can extract YAML by using following image.

![image](https://user-images.githubusercontent.com/4174297/81190994-208b6100-8fd6-11ea-8022-92a806c4f9e6.png)

**Comment by vineetmimrot** [comment]
Kindly close it if your query is resolved. Thanks.

**Comment by allanmoller** [comment]
I know how to create and YAML pipeline using the portal, what I am referring to is doing it automatically, using and ARM template and an extension. In extension JSON a standard buildDefinition is defined like this:

vss-extension.json
`              "buildDefinition": {
                  "queue": "HostedVS2017",
                  "templateFile": "Files/BuildDefinitionTemplates/AspNetBuild.json"
              }
`

But this refers to legacy pipelines, and not a YAML pipeline from repo! looking at output from "f12" when in azure devops portal, i noticed request had a "process" value in body that referred to the YAML file, so i tried this:


vss-extension.json
`
.......          
"configuration": {
              "imports": [
                  "Files/Configuration/ArmEndpointConfiguration.json"
              ],
              "source": {
                  "repository": {
                    "id": "https://github.com/bishal-pdMSFT/project-aspnet-windowswebapp",
                    "defaultBranch": "master"
                },
                "process": {
                  "yamlFilename": "azure-pipelines.yml",
                  "type": 2
               }
              }
......
`
But with no luck, so trying to guess how the configuration should look, but not working out that well :-) so hopefully someone could tell me, or point me to a solution?

**Comment by allanmoller** [comment]
:-) just realized that this was posted under wrong repo, sry for inconvenience
